name: Asana api generation
run-name: ${{ github.actor }} is generating apis
on:
  workflow_dispatch:
    inputs:
      userEmail:
        description: 'User email which will be used for commit'     
        required: true
        default: 'github-actions@github.com'
      masterBranch:
        description: "Branch for creating PR"
        required: true
        default: "main"
jobs:
  Generate-Apis:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Use JAVA 8 - OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run generate script
        run: ./generate_api.sh
      - name: Commit files
        run: |
          git config --local user.email  ${{ github.event.inputs.userEmail }}
          git config --local user.name "${GITHUB_ACTOR}"
          current_date_time=$(date '+%Y_%m_%d__%H_%M');
          branch_name="generated_apis_$current_date_time";
          git checkout -b "$branch_name";
          [ -z  $(git status --porcelain) ] && { echo "Nothing to commit"; } || {
            echo "Modified=true" >> $GITHUB_ENV
            git add -A && git commit -m "Generated ASANA apis using openapi-generator.\n Generated by ${GITHUB_ACTOR}, JOB:${GITHUB_JOB}/${GITHUB_RUN_ID}}";
            git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git "$branch_name";
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        if: ${{ env.Modified == 'true' }}
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: ${{ github.event.inputs.masterBranch }}
          title: Generaed apis
          label: automatic,apiGeneration
      - run: echo "🍏 This job's status is ${{ job.status }}."
