name: Generate APIs
run-name: ${{ github.actor }} is generating apis
on: workflow_dispatch
jobs:
  Generate-Apis:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "8"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generation setup
        run: mkdir -p openapi_templates
      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          generator-tag: v6.2.1
          openapi-url: https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml
          template-dir: openapi_templates
          config-file: config.yml
      - name: Post process
        run: ./generate_api.sh
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Modified=true" >> $GITHUB_ENV
          fi
      - name: Commit code changes
        if: ${{ env.Modified == 'true' }}
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[AUTO] "
          commit_message: "Generated from OpenAPI Generator"
          force: false
          target_branch: openapi_generator
      - name: Create a pull requset
        if: ${{ env.Modified == 'true' }}
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Initiated by ${GITHUB_ACTOR}<br>"
          title: ${{ github.event.commits[0].message }}
          label: auto-gen
      - run: echo "🍏 This job's status is ${{ job.status }}."
